:sparkles:  Reintroduce multi-file support
konveyor/editor-extensions pull request #124
Opened 2024-11-29 21:00 UTC by rszwajko

Refactor and where necessary partially revert the code introduced in feature/kai branch.

Changes:
1. base the webview view/apply/discard actions on state property
   localChanges which contains parsed and localized resolutions.
2. refactor async code in analyzer client
   a) use promisfied versions of exec and setTimeout
   b) create synchronous version of  canAnalyze
   c) extract extension state mutations to dedicated fire*Change methods
   d) introduce ServerState enum
3. save raw response (solutionData) and scope using loadSolution command
   to better link those entities.
4. re-create Uri objects received in the message handler from webviews.
   After crossing the iframe boundary only data props are preserved.
5. remove triggering checkServerStatus message from the webviews as the
   new onDataChanged event should provide the notifications already
6. derive the list of unprocessed resolution from LocalChange.state
7. create Scope interface - to be extended with more combinations in the
   future.
8. add scope property to Solution and allow viewing incidents without
   running server. Together this allows end-to-end testing with mocks.
9. name error property in GetSolutionResult(ideal response) for better
   alignment with SolutionResponse(actual response)

2024-11-29 21:01 UTC, rszwajko commented
https://github.com/user-attachments/assets/bb3c4ab3-560c-4f83-aa4d-c9f97b802044

2024-12-02 16:38 UTC, ibolton336 requested changes

2024-12-02 16:38 UTC, ibolton336 commented on webview-ui/src/components/AnalysisPage.tsx
> +  if (!serverRunning && !hasViolations) {
Is this just for local development purposes?

2024-12-02 16:45 UTC, ibolton336 approved these changes

2024-12-02 16:46 UTC, ibolton336 commented on webview-ui/src/components/AnalysisPage.tsx
> +  if (!serverRunning && !hasViolations) {
I think we should add a follow up PR to disable server dependent actions like getSolution / runAnalysis if the server is not running while keeping this "new" use case in consideration.

2024-12-02 16:46 UTC, merged