Move and adjust properties from MTA extension manifest
konveyor/editor-extensions pull request #14
Opened 2024-09-23 18:49 UTC by rszwajko

2024-09-23 18:59 UTC, ibolton336 approved these changes

2024-09-23 19:26 UTC, djzager requested changes

2024-09-23 19:26 UTC, djzager commented on vscode/resources/mta_mtr_icon.png
Since we are under the konveyor org, cncf owned, I believe this should be the konveyor logo. Maybe we use this one? https://github.com/konveyor-ecosystem/kai-vscode-plugin/blob/main/resources/konveyor-icon-color.png

2024-09-23 21:24 UTC, rszwajko commented on vscode/resources/mta_mtr_icon.png
@djzager 
My understanding was that this plugin will replace the MTA plugin in the VS Code marketplace so we want to maintain some sense of continuity.

2024-09-24 00:08 UTC, djzager commented on vscode/resources/mta_mtr_icon.png
Then we would need to fork this repo for producing such a replacement plugin because we cannot put red hat product stuff in cncf owned repositories.

2024-09-24 00:38 UTC, djzager commented on vscode/resources/mta_mtr_icon.png
That is to say. I agree we will need to figure out how to make this plugin replace the MTA plugin, we just can't have product bits in these konveyor/* repositories.

2024-09-24 22:08 UTC, dymurray commented on vscode/resources/mta_mtr_icon.png
+1 on branding this under Konveyor right now. I fully support the idea to template out the rendering to make branding changes easy down the line

2024-09-25 13:24 UTC, djzager approved these changes

2024-09-25 13:30 UTC, merged